/**
 * Exports Image Paths
 * @function Images
 */
export const Images = {
  noData: require('@assets/Images/no-data.json'),
  Loading: require('@assets/Images/loading.json'),
  payment: require('@assets/Images/payment.json'),
  Typing: require('@assets/Images/typing.json'),
  logo: require('@assets/Images/logo.png'),
  mainscreen: require('@assets/Images/mainscreen.png'),
  profile: require('@assets/Images/profile.png'),
  profile1: require('@assets/Images/profile1.png'),
  settingscreenimg: require('@assets/Images/settingscreenimg.png'),
  rightarrow: require('@assets/Images/rightarrow.png'),
  edit: require('@assets/Images/edit.png'),
  logout: require('@assets/Images/logout.png'),
  blockedprofile: require('@assets/Images/blockedprofile.png'),
  interest: require('@assets/Images/interest.png'),
  myfavrouite: require('@assets/Images/myfavrouite.png'),
  winks: require('@assets/Images/winks.png'),
  mysubscription: require('@assets/Images/mysubscription.png'),
  myvisitors: require('@assets/Images/myvisitors.png'),
  mypreferences: require('@assets/Images/mypreferences.png'),
  setMenu: require('@assets/Images/setMenu.png'),
  Location: require('@assets/Images/Location.png'),
  event: require('@assets/Images/event.png'),
  dutchFlag: require('@assets/Images/dutchFlag.png'),
  frenchFlag: require('@assets/Images/frenchFlag.png'),
  germanFlag: require('@assets/Images/germanFlag.png'),
  engFlag: require('@assets/Images/engFlag.png'),
  headerBack: require('@assets/Images/headerBack.png'),
  BackArrow: require('@assets/Images/BackArrow.png'),
  BackArrowWhite: require('@assets/Images/BackArrowWhite.png'),
  contact: require('@assets/Images/contact.png'),
  about: require('@assets/Images/about.png'),
  close: require('@assets/Images/close.png'),
  downarrow: require('@assets/Images/downarrow.png'),
  changePassword: require('@assets/Images/changePassword.png'),
  character: require('@assets/Images/character.png'),
  blankImage: require('@assets/Images/placeholder.png'),
  faqImage: require('@assets/Images/faq.png'),
  termsImage: require('@assets/Images/terms.png'),
  playIcon: require('@assets/Images/playIcon.png'),
  privacyImage: require('@assets/Images/Privacy.png'),
  matchImage: require('@assets/Images/Match.png'),
  smileHeart: require('@assets/Images/smileHeart.png'),
  Heart: require('@assets/Images/Heart.png'),
  blackHeart: require('@assets/Images/blackHeart.png'),
  realHeart: require('@assets/Images/realHeart.png'),
  darkHeart: require('@assets/Images/darkHeart.png'),
  loveChat: require('@assets/Images/LoveChat.png'),
  Vector: require('@assets/Images/Vector.png'),
  blocked: require('@assets/Images/blocked.json'),
  US: require('@assets/Images/US.png'),
  FR: require('@assets/Images/France.png'),
  GR: require('@assets/Images/German.png'),
  DU: require('@assets/Images/Dutch.png'),
  micAnim: require('@assets/lottieFiles/mic.json'),
  waveAnim: require('@assets/lottieFiles/wave.json'),
};
