import { BaseColors, FontFamily } from '@config/theme';
import { Dimensions, StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: BaseColors.white,
  },
  topcontainer: {
    marginTop: 60,
    alignItems: 'center',
  },
  signintext: {
    color: BaseColors.secondary,
    fontSize: 27,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: FontFamily.semiBold,
  },
  remembertext: {
    color: BaseColors.secondary,
    fontSize: 16,
    textAlign: 'center',
    fontFamily: FontFamily.semiBold,
  },
  card: {
    marginHorizontal: 20,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    backgroundColor: BaseColors.white,
    padding: 10,
    borderRadius: 5,
  },
  remembersubtext: {
    marginTop: 50,
    color: BaseColors.primary,
    textAlign: 'center',
    fontSize: 17,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: FontFamily.semiBold,
    marginBottom: 20,
  },
  remembersubtext1: {
    marginTop: 50,
    color: BaseColors.secondary,
    textAlign: 'center',
    fontSize: 17,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: FontFamily.semiBold,
    marginBottom: 20,
  },
  subtitleintext: {
    fontSize: 13,
    marginTop: 5,
    color: BaseColors.black70,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: FontFamily.semiBold,
  },
  signinbutton: {
    width: Dimensions.get('window').width - 50,
    fontFamily: FontFamily.bold,
    marginTop: 40,
  },

  profileimage: {
    marginTop: 10,
    width: 140,
    height: 140,
    resizeMode: 'contain',
  },
  checkbutton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginHorizontal: 5,
  },
  signupbuttontext: {
    fontSize: 17,
    alignItems: 'center',
    textAlign: 'center',
    color: 'white',
    fontWeight: '600',
    fontFamily: 'Montserrat',
  },
  inputmain: {
    marginTop: 40,
    // flex: 2,
    // justifyContent: 'center',
    paddingHorizontal: 20,
  },
  forgotpassword: {
    color: BaseColors.primary,
    fontSize: 12,
    marginTop: 5,
    fontFamily: FontFamily.semiBold,
  },
  input1: {
    borderColor: 'grey',
    height: 50,
    width: Dimensions.get('window').width - 50,
    marginTop: 10,
    padding: 10,
    borderRadius: 15,
    borderWidth: 1,
  },
  Img: {
    height: 60,
    width: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  imgBox: {
    flexDirection: 'row',

    alignItems: 'center',
  },
  imgBox1: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  box: {
    width: 300,
    height: 300,
    backgroundColor: 'white',
    marginBottom: 30,
  },
  text: {
    fontSize: 30,
  },
  container9: {
    fontSize: 14,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'left',
    color: BaseColors.primary,
    fontFamily: 'Montserrat',
  },
  signuptext: {
    fontSize: 14,
    marginTop: 20,
    color: BaseColors.primary,
    fontFamily: FontFamily.medium,
  },
  logintext1: {
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Montserrat',
  },
  signup: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  verification: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  donthaveaccount: {
    color: BaseColors.secondary,
    fontSize: 14,
    marginTop: 20,
    fontFamily: FontFamily.medium,
  },
  circle: {
    height: 120,
    borderRadius: 60,
    width: 120,
    alignSelf: 'center',
  },
  version: { textAlign: 'center', marginTop: 15, color: BaseColors.black90 },
});
