import { StyleSheet, Dimensions, Platform } from 'react-native';
import { BaseColors, FontFamily } from '@config/theme';
import BaseSetting from '@config/setting';

const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;
const IOS = Platform.OS === 'ios';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BaseColors.white,
  },
  imageContainer: {
    height: windowHeight / 2,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  roundView: {
    flex: 1,
    marginTop: -45,
    zIndex: 50,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    backgroundColor: BaseColors.white,
  },
  bio: {
    fontFamily: FontFamily.medium,
    color: BaseColors.secondary,
  },
  threeBtn: {
    zIndex: 11,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundBoxes: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -30,
    zIndex: 50,
  },
  topRound: {
    backgroundColor: BaseColors.white,
    borderWidth: 1,
    borderColor: BaseColors.black40,
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  topMiddleRound: {
    backgroundColor: BaseColors.primary,
    elevation: 5,
    width: 70,
    height: 70,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 15,
  },
  container2: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
  },
  text: {
    color: 'white',
    fontSize: 42,
    lineHeight: 84,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: '#000000c0',
  },
  leftImage: { height: 20, width: 22 },
  profileimage: {
    height: '100%',
    width: '100%',
    alignSelf: 'center',
  },
  signinbutton: {
    width: BaseSetting.nWidth - 30,
  },

  modalStyle: {
    borderTopEndRadius: 50,
    borderTopStartRadius: 50,
  },

  modaltext: {
    fontSize: 20,
    fontFamily: FontFamily.bold,
    color: BaseColors.secondary,
  },
  modalsubtext: {
    fontSize: 14,
    fontFamily: FontFamily.semiBold,
    marginTop: 5,
    marginBottom: 20,
  },
  optcontainer: {},
  centerTxt: {
    fontSize: 20,
    marginTop: 15,
    marginHorizontal: 20,
    fontFamily: FontFamily.semiBold,
    color: BaseColors.secondary,
  },
  label: {
    marginLeft: 15,
    flexGrow: 1,
    fontSize: 16,
    color: BaseColors.secondary,
    fontFamily: FontFamily.semiBold,
  },
  userInfo: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    zIndex: 5,
    width: '100%',
  },
  details: {
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    flexWrap: 'wrap',
  },
  userRow: {
    flexDirection: 'row',
    marginVertical: 5,
    flexBasis: '48%',
    alignItems: 'center',
  },
  iconStyle: {
    marginRight: 5,
  },
  dividerHr: {
    marginRight: windowWidth / 2,
  },
  about: {
    width: '100%',
    marginVertical: 12,
    paddingHorizontal: 20,
  },
  titleTag: {
    fontSize: 22,
    color: BaseColors.secondary,
    fontFamily: FontFamily.medium,
  },
  userTitle: {
    fontSize: 30,
    color: BaseColors.secondary,
    fontFamily: FontFamily.semiBold,
  },
  hobbyCollection: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    flexWrap: 'wrap',
  },
  hobbyData: {
    width: '100%',
    flexDirection: 'row',
  },
  Img: {
    height: 20,
    width: 35,
  },
  backHome: {
    marginTop: IOS ? windowHeight / (13 * 1.3) : windowHeight / (13 * 2),
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    flexDirection: 'row',
  },
  hobby: {
    borderColor: BaseColors.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 50,
    borderWidth: 1,
    backgroundColor: BaseColors.lightPink,
    marginRight: 10,
  },
  galleryTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  galleryImages: {
    height: 100,
    width: 100,
    marginTop: 10,
    borderRadius: 10,
    marginRight: 10,
  },
  images: {
    width: '100%',
    marginVertical: 12,
    paddingHorizontal: 20,
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  getPics: {
    height: BaseSetting.nWidth / 2,
    width: BaseSetting.nWidth / 2.3,
    marginVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: 5,
  },
  LoaderCon: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 100,
  },
  chipStyle: { marginRight: 10, marginVertical: 5 },
  galleryData: { width: '100%', paddingHorizontal: 20, marginTop: 15 },
  seeAll: { flexDirection: 'row', marginRight: 10 },
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setWidth: {
    width: '100%',
  },
  popup: {
    backgroundColor: 'white',
    position: 'absolute',
    width: BaseSetting.nWidth / 2,
    top: windowHeight / 25,
    right: 2,
    padding: 20,
    borderRadius: 10,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  closeButton: {
    color: BaseColors.primary,
  },
  popupText: {
    color: BaseColors.secondary,
    marginVertical: 6,
    fontSize: 16,
    fontFamily: FontFamily.medium,
  },
  desc: {
    color: BaseColors.secondary,
    fontSize: 16,
    fontFamily: FontFamily.medium,
  },
  modalCon: {
    borderTopRightRadius: 25,
  },
  deleteOp: {
    marginTop: -35,
    paddingRight: 15,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  btnStyleDel: {
    flexDirection: 'row',
    width: '48%',
    justifyContent: 'space-evenly',
  },
  btnStyle: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-evenly',
    paddingVertical: 15,
  },
  multi: {
    fontSize: 18,
    marginHorizontal: 20,
    marginTop: 25,
    color: BaseColors.secondary,
    fontFamily: FontFamily.medium,
  },
  deleteImg: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  topTitle: {
    color: BaseColors.secondary,
    fontSize: 20,
    fontFamily: FontFamily.medium,
    marginBottom: 10,
  },
  btnIn: { paddingHorizontal: 15, width: 150 },
  headLine: {
    alignSelf: 'center',
    height: 5,
    width: 70,
    backgroundColor: BaseColors.primary,
    borderBottomStartRadius: 5,
    borderBottomEndRadius: 5,
  },
  modal: {
    paddingTop: 5,
    borderTopEndRadius: 40,
    borderTopStartRadius: 40,
  },
  modalTitle: {
    alignSelf: 'center',
    fontSize: 20,
    marginVertical: 15,
    color: BaseColors.secondary,
    fontFamily: FontFamily.bold,
  },
  uploadSelect: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: BaseColors.black20,
    paddingVertical: 20,
  },
  SelectText: {
    flex: 1,
    fontFamily: FontFamily.medium,
    fontSize: 15,
    color: BaseColors.secondary,
    marginHorizontal: 10,
  },
  videoStyle: {
    height: BaseSetting.nHeight * 0.3,
    width: BaseSetting.nWidth - 40,
    backgroundColor: BaseColors.black,
    borderRadius: 10,
    overflow: 'hidden',
    justifyContent: 'center',
    marginVertical: 15,
  },
  VideoLoader: {
    position: 'absolute',
  },
  matched: {
    paddingVertical: 10,
    borderColor: BaseColors.primary,
    borderWidth: 1,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginTop: 10,
  },
  charDevide: {
    borderBottomColor: BaseColors.black80,
    borderBottomWidth: 1,
    height: 5,
    width: '90%',
  },
  charContainer: {
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 6,
  },
  charTitle: {
    fontSize: 16,
    fontFamily: FontFamily.semiBold,
    color: BaseColors.textColor,
  },
  touchTitle: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 5,
  },
  deletecontainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    paddingVertical: 10,
  },
  deleteText: {
    fontSize: 15,
    color: BaseColors.red,
    fontFamily: FontFamily.medium,
  },
  modalText: {
    textAlign: 'center',
    fontFamily: FontFamily.semiBold,
    color: BaseColors.secondary,
    fontSize: 18,
    marginTop: 30,
    marginBottom: 5,
  },
  modalText1: {
    textAlign: 'center',
    fontFamily: FontFamily.regular,
    color: BaseColors.secondary,
    fontSize: 14,
    marginTop: 30,
    marginBottom: 40,
  },
  btnCon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
});
